import {manager} from 'src';

export const runTest = () => {
	const {
		scrapers: {mp},
	} = manager({mp: {setMovements: () => {}, findMovement: () => undefined}});

	mp.login([
		{
			name: 'orguseridp',
			value: '531535528',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1752148199.631084,
			size: 19,
			httpOnly: false,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
		{
			name: 'orguserid',
			value: '99HT0H9H99Z7',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1752148199.631177,
			size: 21,
			httpOnly: false,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
		{
			name: 'orgnickp',
			value: 'MIXAR_SA',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1752148199.631006,
			size: 16,
			httpOnly: false,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
		{
			name: 'ssid',
			value:
				'ghy-060507-MXWx8uaaPkGxEQTLsgX1YeRkpRopp4-__-531535528-__-1812196200195--RRR_0-RRR_0',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1752148199.630883,
			size: 88,
			httpOnly: true,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
		{
			name: 'ftid',
			value: 'dji9rm2NyvflpcTdEmBu2nI9KxwvBqqt-1717588148912',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1752148199.631118,
			size: 50,
			httpOnly: true,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
		{
			name: '_mldataSessionId',
			value: '46df54f8-5533-4cf8-b78c-b6e6b681d470',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1717589998,
			size: 52,
			httpOnly: false,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
		{
			name: '_d2id',
			value: '38cb32be-f1ef-4b51-a834-f8d6c9593d73-n',
			domain: '.mercadopago.com.ar',
			path: '/',
			expires: 1749124185.782863,
			size: 43,
			httpOnly: false,
			secure: true,
			session: false,
			sameSite: 'None',
			priority: 'Medium',
			sameParty: false,
			sourceScheme: 'Secure',
		},
	]);

	console.log(mp.getSessionCookies());
	mp.scrap(true);
};
